In [1]:
import numpy as np

In [2]:
a = np.array([(1,2,3), (3,4,5)])
b = np.array([(1,2,3), (3,4,5)])

In [3]:
a

array([[1, 2, 3],
       [3, 4, 5]])

In [4]:
b

array([[1, 2, 3],
       [3, 4, 5]])

In [5]:
# Print the maximum of the matrix
a.max()

5

In [6]:
# Sum up all elements
a.sum()

18

In [7]:
# Calculate the square root
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [1.73205081, 2.        , 2.23606798]])

In [8]:
# Calculate the standard deviation
np.std(a)

1.2909944487358056

In [9]:
# Matrix Addition
a+b

array([[ 2,  4,  6],
       [ 6,  8, 10]])

In [10]:
# Matrix Division
a/b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
# Matrix Subtraction
a-b

array([[0, 0, 0],
       [0, 0, 0]])

In [12]:
# Element-wise matrix multiplication
a*b

array([[ 1,  4,  9],
       [ 9, 16, 25]])

In [13]:
# Stacking vertically
np.vstack((a,b))

array([[1, 2, 3],
       [3, 4, 5],
       [1, 2, 3],
       [3, 4, 5]])

In [14]:
# Stacking horizontally
np.hstack((a,b))

array([[1, 2, 3, 1, 2, 3],
       [3, 4, 5, 3, 4, 5]])

In [16]:
# Transform matrix to one dimension
np.ravel(a)

array([1, 2, 3, 3, 4, 5])

In [20]:
c = np.array([(1,2,3), (3,4,5), (5,6,7)])
d = np.array([(1,2,3), (3,4,5), (5,6,7)])
np.matmul(c,d)

array([[22, 28, 34],
       [40, 52, 64],
       [58, 76, 94]])